export interface ReceitaModel {
	atividade_principal: any
	data_situacao: string
	tipo: string
	nome: string
	atividades_secundarias: any
	qsa: any
	situacao: string
	bairro: string
	logradouro: string
	numero: string
	cep: string
	municipio: string
	fantasia: string
	porte: string
	abertura: string
	natureza_juridica: string
	uf: string
	cnpj: string
	ultima_atualizacao: string
	status: string
	complemento: string
	email: string
	telefone: string
	efr: string
	motivo_situacao: string
	situacao_especial: string
	data_situacao_especial: string
	capital_social: string
	extra: any
	billing: any
}